### Numerical Python (Numpy)
- **_ndarray_** , a fast and space-efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities
- Standard mathematical functions for fast operations on entire arrays of data without having to write loops
- Tools for reading/writing array data to disk and working with memory-mapped files
- Linear algebra, random number generation, and Fourier transform capabilities
- Tools for integrating code written in C, C++, and Fortran

### Array creation functions
|Function          | Description
|------------------|------------------------------------
| array            | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default.
| asarray          | Convert input to ndarray, but do not copy if the input is already an ndarray
| arange           | Like the built-in range but returns an ndarray instead of a list.
| ones, ones_like  | Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.
| zeros, zeros_like | Like ones and ones_like but producing arrays of 0’s instead
| empty, empty_like | Create new arrays by allocating new memory, but do not populate with any values like zones and zeros
| eye, identity     | Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

### The NumPy ndarray: A Multidimensional Array Object

In [2]:
import numpy as np
divider = '-' * 50
data = [6, 7.5, 8, 0, 1]
arr1 = np.array(data)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print('Array type:', type(arr2))
print('printing  :', arr2)
print('dimension :', arr2.ndim)
print('size of arr:', arr2.shape)              # a tuple undicating the size of each demension
print('Data type arr2 :', arr2.dtype)               # dtype == data type
print('Data type arr1 :', arr1.dtype)
print(divider)
# ---------------------------------
zeroArray = np.zeros(10)
print(zeroArray)
print()
zero3Array = np.zeros((3, 6))
print(zero3Array)
print()
empty = np.empty((2, 3, 2))    # it will return uninitialized garbage values.
print(empty)
print()
npRange = np.arange(15)        # like range(15)
print(npRange)

Array type: <class 'numpy.ndarray'>
printing  : [[1 2 3 4]
 [5 6 7 8]]
dimension : 2
size of arr: (2, 4)
Data type arr2 : int64
Data type arr1 : float64
--------------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0.00000000e+000 2.44029516e-312]
  [2.10077583e-312 6.79038654e-313]
  [2.22809558e-312 2.14321575e-312]]

 [[2.35541533e-312 6.79038654e-313]
  [2.22809558e-312 2.14321575e-312]
  [2.46151512e-312 2.41907520e-312]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Data type for ndarray
> Calling astype always create a new array(a copy of the data) even if the new dtype is the same as the old dtype

In [20]:
arr1 = np.ndarray([1, 2, 3], dtype=np.float64)
arr2 = np.ndarray([1, 2, 3], dtype=np.int)
print(arr1.dtype, ',', arr2.dtype)

# convert an int array to float
arr = np.array([1, 2, 3, 4, 5])
print('array type:', arr.dtype)
arr_float = arr.astype(np.float64)
print('converting to float:', arr_float.dtype)
print('float array:', arr_float)
print(divider)

# from float to int
# the dicimal part will be truncated
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.01])
print('Original array:', arr)
arrToInt = arr.astype(np.int32)
print('Converting to int32:', arrToInt)

# from string to flaot
print()
arr = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print('Original:', arr)
to_floa = arr.astype(np.float)
print('to float:', to_floa)

# another way to convert
print()
int_arr = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44], dtype=np.float64)
int_arr = int_arr.astype(calibers.dtype)
print(int_arr.dtype)

float64 , int64
array type: int64
converting to float: float64
float array: [1. 2. 3. 4. 5.]
--------------------------------------------------
Original array: [ 3.7  -1.2  -2.6   0.5  12.9  10.01]
Converting to int32: [ 3 -1 -2  0 12 10]

Original: [b'1.25' b'-9.6' b'42']
to float: [ 1.25 -9.6  42.  ]

float64


### Operations between Arrarys and 
- Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called **_vectorization_**.

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print('- Original Array:', arr)
print('\n- arr * arr:', arr * arr)
print('\n- arr - arr', arr - arr)
print('\n- 1 / arr:', 1 / arr)
print('\n- arr ** 0.5:', arr ** 0.5)

- Original Array: [[1. 2. 3.]
 [4. 5. 6.]]

- arr * arr: [[ 1.  4.  9.]
 [16. 25. 36.]]

- arr - arr [[0. 0. 0.]
 [0. 0. 0.]]

- 1 / arr: [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

- arr ** 0.5: [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### Basic Indexing and Slicing

In [46]:
# One-dimensional arrays are simple; on the surface they act similarly to Python lists:
arr = np.arange(10)
print(arr[5])
print(arr[5:8])

# any modifications to the view will be reflected in the source array
arr[5:8] = 12
print(arr)

print(divider)
arr_slice = arr[5:8]
print(arr)
arr_slice[1] = 12345
print(arr)
arr_slice[:] = 64
print(arr)
# If you want a copy of a slice of an ndarray instead of a view, 
# you will need to explicitly copy the array.
arr_slice2 = arr[5:8].copy()
print(arr_slice2)
print(divider)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[2])
print(arr[0, 2])

5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
--------------------------------------------------
[ 0  1  2  3  4 12 12 12  8  9]
[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]
[64 64 64]
--------------------------------------------------
[7 8 9]
3


### Boolean Indexing 

In [68]:
# suppose data: Bob = 0, Joe = 1, Will = 2
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.array([[0, 0, 0, 0],
                [1, 1, 1, 1],
                [2, 2, 2, 2],
                [0, 0, 0, 0],
                [2, 2, 2, 2],
                [1, 1, 1, 1],
                [1, 1, 1, 1]
                ])
print('Names == Bob:', names == 'Bob')
print('Data for bob:', data[names == 'Bob'], '\n')

# with slice
print(data[names == 'Bob', 2:], '\n')
print(data[names == 'Bob', 3])               # index 3 of the all array

# every thing except 'Bob'
print(divider)
print('Names != Bob', names != 'Bob')
print(data[~(names == 'Bob')])

# Selecting two of the three names
print(divider)
mask = (names == 'Bob') | (names == 'Will')
print(mask)
print(data[mask])

# Setting Values
print(divider)
data[data > 1] = 3
print(data)

print(divider)
data[names != 'Joe'] = 7
print(data)

Names == Bob: [ True False False  True False False False]
Data for bob: [[0 0 0 0]
 [0 0 0 0]] 

[[0 0]
 [0 0]] 

[0 0]
--------------------------------------------------
Names != Bob [False  True  True False  True  True  True]
[[1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]
 [1 1 1 1]
 [1 1 1 1]]
--------------------------------------------------
[ True False  True  True  True False False]
[[0 0 0 0]
 [2 2 2 2]
 [0 0 0 0]
 [2 2 2 2]]
--------------------------------------------------
[[0 0 0 0]
 [1 1 1 1]
 [3 3 3 3]
 [0 0 0 0]
 [3 3 3 3]
 [1 1 1 1]
 [1 1 1 1]]
--------------------------------------------------
[[7 7 7 7]
 [1 1 1 1]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [1 1 1 1]
 [1 1 1 1]]


### Fancy Indexing
- Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
- Fancy indexing, unlike slicing, always copies the data into a new array.

In [77]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)
print(divider)
print(arr[[4, 3, 0, 6]])
print(divider)
print(arr[[-3, -5, -7]])

print(divider)
arr = np.arange(32).reshape((8, 4))
print(arr)

print(divider)
# Select the elements (1, 0), (5, 3), (7, 1), and (2, 2)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
print(divider)
# 
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
--------------------------------------------------
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
--------------------------------------------------
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
--------------------------------------------------
[ 4 23 29 10]
--------------------------------------------------
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
